name: Build Anime Voice APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -B

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AnimeVoiceApp
          path: target/*.apk
          
